version: "3"

networks:
    web:
        external: true
    internal:
        external: false

services:
    blog:
        image: wordpress:4.9.8-apache
        environment:
            WORDPRESS_DB_PASSWORD:
        labels:
            - traefik.backend=blog
            - traefik.frontend.rule=HOST:blog.wifienabler.com
            - traefik.docker.network=web
            - traefik.port=80
        networks:
            - internal
            - web
        depends_on:
            - mysql        

    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD:
        networks:
            - internal
        labels:
            - traefik.enable=false

    adminer:
        image: adminer:4.6.3-standalone
        labels:
            - traefik.backend=adminer
            - traefik.frontend.rule=HOST:db-admin.wifienabler.com
            - traefik.docker.network=web
            - traefik.port=8080
        networks:
            - internal
            - web
        depends_on:
            - mysql
